### PR TITLE
Issue resolved "Error in main.py"

### PR DESCRIPTION
**Pull request by parth1993**
Issue is with bitwise_and of opencv, it's better to use numpy's bitwise_and. Results are same.

### CODE REVIEW

**Comment by WillBrennan** [comment]
Hey - This looks good, I'll merge it in. I updated travis.ci so now the issue with cv2.bitwise_and is appearing on them.

**Comment by parth1993** [comment]
Is the issue resolved? And what's the issue with travis.cl?

**Comment by WillBrennan** [comment]
Looks like it. 

Issue with travis CI was using `sudo apt-get install -y python-opencv` and how it couldn't be accessed within the virtualenv that travis uses. Swapping to `pip install opencv-python` fixed the issue.

**Comment by parth1993** [comment]
Cool. That's great!

**Comment by parth1993** [comment]
Btw I used your script in my colour detection package. So it was working
great just need to threshold the algorithm so that it can differentiate
between object and human skin.

**Pull request merged**
